lib/software: Fix return types
Currently, when building genwqe on 32-bits arch, it fails with the
following error:

  software.c:537:9: error: conflicting types for ‘gzseek64’
   z_off_t gzseek64(gzFile file, z_off64_t offset, int whence)
           ^~~~~~~~
  In file included from software.c:23:0:
  /usr/include/zlib.h:1693:30: note: previous declaration of ‘gzseek64’
  was here
      ZEXTERN z_off64_t ZEXPORT gzseek64 OF((gzFile, z_off64_t, int));
                                ^~~~~~~~
This is because a 32bits gz function() should use z_off64_t instead of
z_off_t type.