lib/hardware: Fix printf for size_t
There are some debugging printf being called with %ld other than %zd.
This cause build on 32-bits platform, showing the following message:

 In file included from hardware.c:22:0:
 hardware.c: In function ‘h_inflate’:
 ./wrapper.h:90:22: error: format ‘%ld’ expects argument of type ‘long
 int’, but argument 3 has type ‘size_t {aka unsigned int}’
 [-Werror=format=]
     fprintf(zlib_log, "hhh " fmt, ## __VA_ARGS__); \
                       ^
 hardware.c:1456:5: note: in expansion of macro ‘hw_trace’
      hw_trace("    Suppress Z_STREAM_END %ld %ld\n",
      ^~~~~~~~
 ./wrapper.h:90:22: error: format ‘%ld’ expects argument of type ‘long
 int’, but argument 4 has type ‘size_t {aka unsigned int}’
 [-Werror=format=]
     fprintf(zlib_log, "hhh " fmt, ## __VA_ARGS__); \

This patch just fix this issue.t t